apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortunecooky-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: fortunecooky
  replicas: 3
  template:
    metadata:
      name: fortunecooky-tmpl
      labels:
        app: fortunecooky
    spec:
      containers:
        - name: fortunecooky
          image: fortunecooky:latest
          ports:
            - containerPort: 5000
