# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: fortunecooky-svc
spec:
  type: NodePort
  selector:
    app: fortunecooky
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
